spring.application.name: transaction-filter-topology

spring.cloud:
  stream.bindings:
    filterForTransferTransaction-in-0:
      destination: transactions
    filterForTransferTransaction-out-0:
      destination: transfer-transactions

  function:
    definition: filterForTransferTransaction

