server.port: 9090
management.endpoints.web.exposure.include: kafkastreamstopology,bindings,metrics,info,health,prometheus
management.health.binders.enabled: true
management.endpoint.health.show-details: ALWAYS

spring.application.name: account-balance-calculation-topology

spring.cloud:
  stream:
    bindings:
      calculateAccountBalance-in-0:
        destination: transactions
      calculateAccountBalance-out-0:
        destination: account-balances

    kafka:
      streams:
        binder:
          configuration:
            schema.registry.url: http://localhost:8081

  function:
    definition: calculateAccountBalance

