server:
  port: 8004
spring:
  application:
    name: loan-evaluation-topology
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
loan:
  input:
    topic: loan-requests
  output:
    topic: loan-evaluation-results