



spring:
  main:
    web-application-type: none
  application:
    name: transaction-producer
  cloud.stream.kafka.binder:
    brokers: localhost
    defaultBrokerPort: 9092
    enableObservation: true
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry: http://localhost:8081
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: prometheus

transaction-producer:
  topic: transactions
  fixed-rate: 1000